package session_test

import (
	"os/exec"
	"strings"
	"testing"
)

// TestSessionStaysLightEnoughForAWindow is a layering rule with teeth.
//
// This package is imported by both sides of the privilege boundary: the
// privileged component that runs a tunnel, and the unprivileged window that
// authenticates a person and then hands over a token. The window's build has to
// stay independent — it needs cgo and a toolkit and is built per platform, while
// the command-line client is static and cross-compiled from one machine — and it
// must never pull in the patched wireguard-go checkout, which is generated by
// build.sh and is not in the repository at all.
//
// One import is all it takes. Before internal/paths existed, this package
// reached into internal/runtime for the run directory — a string — and brought
// netlink, the tunnel device and every platform file along with it. Nothing
// failed; the graphical client would simply have stopped being buildable on its
// own, at whatever later moment somebody noticed.
func TestSessionStaysLightEnoughForAWindow(t *testing.T) {
	out, err := exec.Command("go", "list", "-deps", ".").Output()
	if err != nil {
		t.Fatalf("go list -deps: %v", err)
	}

	forbidden := []string{
		"golang.zx2c4.com/wireguard",     // the generated fork
		"github.com/vishvananda/netlink", // the platform layer
		"github.com/encedo/encedo-wg-hsm/internal/runtime",
	}
	for _, dep := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		for _, bad := range forbidden {
			if dep == bad || strings.HasPrefix(dep, bad+"/") {
				t.Errorf("internal/session depends on %s.\n"+
					"That is the import that ends the graphical client's independent build.\n"+
					"Whatever was needed from there belongs in internal/paths, or on the far\n"+
					"side of the boundary in the package that runs the tunnel.", dep)
			}
		}
	}
}
